// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BlazorPart.Models
{
    public partial class BasePart
    {
        public string Cspecifications { get; set; }
        public decimal? Inw { get; set; }
        public decimal? Icw { get; set; }
        public string Cunits { get; set; }
        public decimal? Ineedcheck { get; set; }
        public string Cinrule { get; set; }
        public string Coutrule { get; set; }
        public decimal? Ilength { get; set; }
        public decimal? Iwidth { get; set; }
        public decimal? Iheight { get; set; }
        public string Cusetype { get; set; }
        public string Cdefine1 { get; set; }
        public string Cdefine2 { get; set; }
        public DateTime? Ddefine3 { get; set; }
        public DateTime? Ddefine4 { get; set; }
        public decimal? Idefine5 { get; set; }
        public string Cmemo { get; set; }
        public DateTime? Dexpiredate { get; set; }
        public string Calias { get; set; }
        public string Cerpcode { get; set; }
        public decimal? Csafeqty { get; set; }
        public decimal? Ineedwarn { get; set; }
        public string Id { get; set; }
        public string Cstatus { get; set; }
        public string Cpartnumber { get; set; }
        public string Cpartname { get; set; }
        public string Ctype { get; set; }
        public string Cdefaultware { get; set; }
        public string Cdefaultcargo { get; set; }
        public string Cversion { get; set; }
        public string Cbarrule { get; set; }
        public string Cdefaultvendor { get; set; }
        public decimal? Cvolume { get; set; }
        public DateTime? Createtime { get; set; }
        public string Createowner { get; set; }
        public DateTime? Lastupdatetime { get; set; }
        public string Lastupdateowner { get; set; }
        public decimal? Mtype { get; set; }
        public decimal? Bonded { get; set; }
        public decimal? ExpDays { get; set; }
        public string Productcode { get; set; }
        public decimal? Boxnum { get; set; }
        public string Unit { get; set; }
        public int? NeedSerial { get; set; }
        public decimal? Csafeqtyceiling { get; set; }
    }
}